# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.evonames.com/com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.evonames.com.rb'

describe Whois::Parsers::WhoisEvonamesCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.evonames.com/com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("endinblue.com")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2017-08-08"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2018-02-09 15:36:33"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2018-08-08"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("1418")
      expect(subject.registrar.name).to eq("DANESCO TRADING LTD")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].id).to eq("MR_11625649WP")
      expect(subject.registrant_contacts[0].name).to eq("WhoisProtectService.net")
      expect(subject.registrant_contacts[0].organization).to eq("PROTECTSERVICE, LTD.")
      expect(subject.registrant_contacts[0].address).to eq("Agios Fylaxeos 66 and Chr. Perevou 2, Kalia Court, off. 601")
      expect(subject.registrant_contacts[0].city).to eq("Limassol")
      expect(subject.registrant_contacts[0].zip).to eq("3025")
      expect(subject.registrant_contacts[0].state).to eq("")
      expect(subject.registrant_contacts[0].country_code).to eq("Cyprus")
      expect(subject.registrant_contacts[0].phone).to eq("+357.95713635")
      expect(subject.registrant_contacts[0].fax).to eq("+357.95713635")
      expect(subject.registrant_contacts[0].email).to eq("endinblue.com@whoisprotectservice.net")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].id).to eq("MR_11625649WP")
      expect(subject.admin_contacts[0].name).to eq("WhoisProtectService.net")
      expect(subject.admin_contacts[0].organization).to eq("PROTECTSERVICE, LTD.")
      expect(subject.admin_contacts[0].address).to eq("Agios Fylaxeos 66 and Chr. Perevou 2, Kalia Court, off. 601")
      expect(subject.admin_contacts[0].city).to eq("Limassol")
      expect(subject.admin_contacts[0].zip).to eq("3025")
      expect(subject.admin_contacts[0].state).to eq("")
      expect(subject.admin_contacts[0].country_code).to eq("Cyprus")
      expect(subject.admin_contacts[0].phone).to eq("+357.95713635")
      expect(subject.admin_contacts[0].fax).to eq("+357.95713635")
      expect(subject.admin_contacts[0].email).to eq("endinblue.com@whoisprotectservice.net")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].id).to eq("MR_11625649WP")
      expect(subject.technical_contacts[0].name).to eq("WhoisProtectService.net")
      expect(subject.technical_contacts[0].organization).to eq("PROTECTSERVICE, LTD.")
      expect(subject.technical_contacts[0].address).to eq("Agios Fylaxeos 66 and Chr. Perevou 2, Kalia Court, off. 601")
      expect(subject.technical_contacts[0].city).to eq("Limassol")
      expect(subject.technical_contacts[0].zip).to eq("3025")
      expect(subject.technical_contacts[0].state).to eq("")
      expect(subject.technical_contacts[0].country_code).to eq("Cyprus")
      expect(subject.technical_contacts[0].phone).to eq("+357.95713635")
      expect(subject.technical_contacts[0].fax).to eq("+357.95713635")
      expect(subject.technical_contacts[0].email).to eq("endinblue.com@whoisprotectservice.net")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(4)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("ns1.storeland.ru")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("ns2.storeland.ru")
      expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[2].name).to eq("ns3.storeland.ru")
      expect(subject.nameservers[3]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[3].name).to eq("ns4.storeland.ru")
    end
  end
end
